name: Deploy to GitHub Pages
on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Deploy to GitHub Pages'

jobs:
  deploy_gh_pages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.2]
    steps:
    - name: check disk space and free
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: install Node.js requirements
      run: npm install
    - name: install python
      run: pip3 install -r visualization/requirements.txt
    # - name: build visualization
    #   run: npm run build-viz-linux
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: visualization/vis-master/dist
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
