name: Deploy to GitHub Pages
on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Deploy to GitHub Pages'

jobs:
  deploy_gh_pages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.2]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: npm install
    - run: pip3 install -r visualization/requirements.txt
    - run: npm run build-viz-linux
      env:
        GH_TOKEN: ${{secrets.GH_TOKEN}}
    -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: visualization/vis-master/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
